version: '3.8'
services:
  app:
    build: .
    container_name: wk_crm_laravel
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: wk_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
